// @ts-check
// Post-bundle pass over every client-rendered route's bootstrap HTML.
//
// Tachyon 26.33 renders Tac in the client, so a route ships as a small
// bootstrap document. Two things still belong in that document's <head>:
//
//   1. The site stylesheet. The compiler emits shared/styles/app.css as a
//      static asset from the `import '../styles/app.css'` in imports.js, but
//      does not link it, so the page would render unstyled until — and only
//      if — JavaScript ran. Linking it here keeps first paint styled.
//   2. A per-route <title>. With no server-rendered subtree, crawlers and
//      tab titles would otherwise see the generic shell title.
//   3. The viewport meta. Without it a phone assumes a ~980px layout viewport
//      and scales the whole page down to fit — the site rendered at 38% on a
//      375px device, which reads as "zoomed out". The bootstrap document ships
//      only <meta charset>, so this is the one place to add it.
//
// It also emits the redirect stubs listed below.

import { mkdir, readdir, readFile, writeFile } from 'fs/promises';
import path from 'path';

const STYLESHEET = '/shared/styles/app.css';
// No `maximum-scale` or `user-scalable=no`: capping zoom breaks WCAG 1.4.4,
// and a design system's own site is the last place to do that.
const VIEWPORT = '<meta name="viewport" content="width=device-width, initial-scale=1">';
const MARK = '<!--duvay-head-->';

/**
 * Routes that have moved, and where they moved to.
 *
 * These are emitted as client-side stubs rather than server rules because the
 * docs site is a static bundle: GitHub Pages has no redirect configuration, so
 * there is nowhere to put a 301. A stub costs one extra document per entry and
 * works wherever the bundle is hosted, including `ty preview`.
 *
 * Keep the list short. An entry earns its place by having been linked from
 * somewhere we do not control — a bookmark, a search result, another site.
 */
const REDIRECTS = {
  // Renamed: the convention is DuVay's own, so it carries the `w-` prefix that
  // every other DuVay concept does rather than borrowing Vue's `v-`.
  '/docs/v-model': '/docs/w-model',
};

/** Every index.html under a root, recursively. */
async function routeDocuments(root) {
  const found = [];
  async function walk(dir) {
    for (const entry of await readdir(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) await walk(full);
      else if (entry.name === 'index.html') found.push(full);
    }
  }
  await walk(root);
  return found;
}

/**
 * The redirect runtime, served as a file rather than inlined.
 *
 * The site sends `script-src 'self'`, which blocks inline scripts outright — an
 * inline `location.replace` here was silently dropped by CSP, leaving the meta
 * refresh to do the work and take the fragment with it. A same-origin file is
 * allowed, so this is what actually runs.
 *
 * It reads its destination from the document's canonical link, so one file
 * serves every redirect and the stub stays declarative.
 */
const REDIRECT_SCRIPT = `// Generated by tac.config.js. Do not edit.
var canonical = document.querySelector('link[rel="canonical"]');
if (canonical) {
  // replace, not assign: Back should return where the reader came from rather
  // than re-entering the redirect.
  location.replace(canonical.getAttribute('href') + location.search + location.hash);
}
`;

const REDIRECT_SCRIPT_PATH = '/shared/scripts/duvay-redirect.js';

/**
 * A redirect document.
 *
 * Two mechanisms, because each covers what the other cannot:
 *   - the script preserves the query and fragment, and replaces the history
 *     entry so Back works;
 *   - the `<noscript>` meta refresh covers a reader without JavaScript. It is
 *     scoped to noscript because a meta refresh cannot carry a fragment and
 *     wins the race when both are live.
 *
 * `rel="canonical"` names the real URL for search engines, and doubles as the
 * script's input.
 */
function redirectHtml(from, to) {
  // Trailing slash: the form the site serves, so this lands directly instead of
  // taking a 307 to add it.
  const target = to.endsWith('/') ? to : `${to}/`;
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Moved to ${target}</title>
  <link rel="canonical" href="${target}">
  <meta name="robots" content="noindex">
  <script src="${REDIRECT_SCRIPT_PATH}"></script>
  <noscript><meta http-equiv="refresh" content="0; url=${target}"></noscript>
</head>
<body>
  <p><code>${from}</code> is now <a href="${target}">${target}</a>.</p>
</body>
</html>
`;
}

/** @param {{ targetRoots: Record<string, string> }} context */
export async function postBundle({ targetRoots }) {
  const webRoot = targetRoots.web;
  if (!webRoot) return; // web-only concern

  let patched = 0;
  for (const file of await routeDocuments(webRoot)) {
    let html = await readFile(file, 'utf8');
    if (html.includes(MARK)) continue;
    html = html.replace(
      '</head>',
      `    ${VIEWPORT}\n    <link rel="stylesheet" href="${STYLESHEET}">\n    ${MARK}\n</head>`,
    );
    await writeFile(file, html);
    patched += 1;
  }
  console.log(`[duvay] linked ${STYLESHEET} + viewport into ${patched} route documents`);

  const scriptFile = path.join(webRoot, REDIRECT_SCRIPT_PATH.replace(/^\//, ''));
  await mkdir(path.dirname(scriptFile), { recursive: true });
  await writeFile(scriptFile, REDIRECT_SCRIPT);

  for (const [from, to] of Object.entries(REDIRECTS)) {
    const dir = path.join(webRoot, from.replace(/^\//, ''));
    // A live route at this path would mean the rename never happened, and the
    // stub would silently overwrite the real page.
    const clash = await readFile(path.join(dir, 'index.html'), 'utf8').catch(() => null);
    if (clash && !clash.includes('rel="canonical"')) {
      throw new Error(`[duvay] redirect ${from} would overwrite a real route`);
    }
    await mkdir(dir, { recursive: true });
    await writeFile(path.join(dir, 'index.html'), redirectHtml(from, to));
  }
  console.log(`[duvay] emitted ${Object.keys(REDIRECTS).length} redirect stub(s)`);
}

export default { postBundle };
